const imageList = [
  'photography-compressed/DSC_8535.webp',
  'photography-compressed/DSC_8471.webp',
  'photography-compressed/DSC_8438.webp',
  'photography-compressed/23.webp',
  'photography-compressed/DSC_8354.webp',
  'photography-compressed/DSC_8287.webp',
  'photography-compressed/DSC_8231.webp',
  'photography-compressed/DSC_8212.webp',
  'photography-compressed/DSC_8178.webp',
  'photography-compressed/DSC_8170.webp',
  'photography-compressed/DSC_8090.webp',
  'photography-compressed/2.webp',
  'photography-compressed/22.webp',
  'photography-compressed/21.webp',
  'photography-compressed/20.webp',
  'photography-compressed/19.webp',
  'photography-compressed/18.webp',
  'photography-compressed/17.webp',
  'photography-compressed/16.webp',
  'photography-compressed/15.webp',
  'photography-compressed/14.webp',
  'photography-compressed/13.webp',
  'photography-compressed/12.webp',
  'photography-compressed/11.webp',
  'photography-compressed/10.webp',
  'photography-compressed/9.webp',
  'photography-compressed/8.webp',
  'photography-compressed/7.webp',
  'photography-compressed/6.webp',
  'photography-compressed/5.webp',
  'photography-compressed/4.webp',
  'photography-compressed/3.webp',
  'photography-compressed/1.webp'
];

export default imageList;